apiVersion: api.gensec.ibm.com/v1
kind: VaultEndpoint
metadata:
  name: demo-secret-engine
spec:
  vaultNamespace: root
  path: demo
  mountOptions:
    type: kv-v2
    description: "the mount point for /demo"
    tuneOptions:
        defaultLeaseTTL: 2764810
        forceNoCache: false
        maxLeaseTTL: 315360000
