apiVersion: api.gensec.ibm.com/v1
kind: VaultEndpoint
metadata:
  name: root-mysecrets
spec:
  vaultNamespace: root
  path: mysecrets
  mountOptions:
    type: kv-v2
    description: "the mount point for /mysecrets"
  tuneOptions:
      defaultLeaseTTL: 2764810
      forceNoCache: false
      maxLeaseTTL: 315360000
