apiVersion: api.gensec.ibm.com/v1
kind: SSHRole
metadata:
  name: local-root-ssh-operator
spec:
  signerPath: ssh
  vaultNamespace: root
  roleName: operator
  parameters:
    allowUserCertificates: true
    allowedUsers: "*"
    allowedExtensions: permit-pty,permit-port-forwarding
    defaultExtensions:
      permit-pty: ""
    keyType: ca
    defaultUser: ubuntu
    ttl: 30m0s