--- 
apiVersion: api.gensec.ibm.com/v1
kind: VaultPolicy
metadata: 
  name: region-template
spec: 
  policyName: operator-{{.region}}
  vaultNamespace: root
  policies: 
    paths: 
      - capabilities: 
          - create
          - read
          - list
          - update
          - delete
          - sudo
        path: operator/{{.region}}/*
