--- 
apiVersion: api.gensec.ibm.com/v1
kind: VaultPolicy
metadata: 
  name: local-parent-pki-admin
spec: 
  policyName: pki-admin
  vaultNamespace: parent
  policies: 
    paths: 
      - capabilities: 
          - create
          - read
          - list
          - update
          - delete
          - sudo
        path: pki/*
